version: '3.9'
services:

  authentication:
    extends:
      file: docker-compose-base.yml
      service: authentication
    command: pdm run test
    restart: always
    networks:
      - test-network

  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
    restart: always
    networks:
      - test-network

  api-celery:
    extends:
      file: docker-compose-base.yml
      service: api-celery
    restart: always
    networks:
      - test-network

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis
    restart: always
    networks:
      - test-network

  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq
    restart: always
    networks:
      - test-network

volumes:
  postgres-db:
  redis-cache:
    driver: local
networks:
  test-network:
    name: test-network