version: '3.9'
services:

  authentication:
    build:
      context: .
      args:
        - INSTALL_COMMAND=i-dev
    extends:
      file: docker-compose-base.yml
      service: authentication
    command: pdm run start
    restart: always
    depends_on:
      - postgres
      - redis


  postgres:
    restart: always
    extends:
      file: docker-compose-base.yml
      service: postgres

  redis:
    restart: always
    extends:
      file: docker-compose-base.yml
      service: redis

volumes:
  postgres-db:
  redis_cache:
    driver: local