version: '3.9'
services:

  authentication:
    extends:
      file: docker-compose-base.yml
      service: authentication
    command: bash -c "pdm run test-alembic &&  pdm run integration-test"
    restart: always
    networks:
      - test-network

  api-celery:
    extends:
      file: docker-compose-base.yml
      service: api-celery
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - test-network

  postgres:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5433:5433"
    env_file:
      - .env
    networks:
      - test-network

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - '6380:6380'
    env_file:
      - .env
#    volumes:
#      - redis-test-cache:/data
    command: redis-server --requirepass 3050132596
    networks:
      - test-network

  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - test-network

#  redis-test-cache:
#    driver: local
networks:
  test-network:
    name: test-network