version: '3.9'
services:

  authentication:
    build:
      context: .
      args:
        - INSTALL_COMMAND=i-dev
    container_name: authentication
    volumes:
      - ./app/:/code/app
      - ./app/logs:/code/logs
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
    tty: true

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_cache:/data
    environment:
      #      - REDIS_PASSWORD=3050132596
      - REDIS_IO_THREADS_DO_READS=true
      - REDIS_IO_THREADS=4
    command: redis-server --requirepass 3050132596

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672

volumes:
  postgres-db:
  redis_cache:
    driver: local