version: '3.9'
services:

  authentication:
    build:
      context: .
      args:
        - INSTALL_COMMAND=i-dev
    container_name: authentication
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./app/:/code/app
      - ./app/logs:/code/logs
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - api-celery
    tty: true

  api-celery:
    build:
      context: .
    container_name: celery
    command: pdm run celery -A app.api.tasks worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - rabbitmq
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      #      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
    tty: true

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env
    volumes:
      - redis-cache:/data
    command: redis-server --requirepass 3050132596
    tty: true

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    tty: true

volumes:
  postgres-db:
  redis-cache:
    driver: local