version: '3.9'
services:

  authentication:
    extends:
      file: docker-compose-base.yml
      service: authentication
    command: pdm run dev
    restart: on-failure
    networks:
      - dev-network

  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
    restart: on-failure
    networks:
      - dev-network

  api-celery:
    extends:
      file: docker-compose-base.yml
      service: api-celery
    restart: on-failure
    networks:
      - dev-network

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis
    restart: on-failure
    networks:
      - dev-network

  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq
    restart: on-failure
    networks:
      - dev-network

volumes:
  postgres-db:
  redis-cache:
    driver: local
networks:
  dev-network:
    name: dev-network