version: '3.9'
services:

  authentication:
    build: .
    container_name: authentication
    command: pdm run start
    restart: always
    volumes:
      - ./app/:/code/app
      - ./app/logs:/code/logs
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
    tty: true

volumes:
  postgres-db: