FROM python:3.10
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /code

COPY ./pyproject.toml ./pdm.lock ./pytest.ini /code/

RUN pip install pdm && \
    python -m pdm install -dG test
COPY ./app /code/app/

CMD pdm run pytest -m "unittest"
