"""create_init_table

Revision ID: 0863ca3ad87b
Revises: 
Create Date: 2023-06-06 17:32:46.453609

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0863ca3ad87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role', sa.String(length=10), nullable=False),
                    sa.CheckConstraint("role in ('admin', 'base_user', 'moderator')"),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('nickname', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('birthday', sa.Date(), nullable=True),
                    sa.Column('main_photo', sa.String(length=255), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('nickname')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
