"""add_activate_user_columns

Revision ID: 8f76f49a7105
Revises: 0863ca3ad87b
Create Date: 2023-06-09 10:13:40.083202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f76f49a7105'
down_revision = '0863ca3ad87b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_user_activate', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'is_user_activate')
    # ### end Alembic commands ###
