name: integration_tests

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run integration test inside docker compose
        uses: actions/checkout@v3
        with:
          compose-file: "./docker-compose-test.yml"

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
