name: integration_tests

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make .env file and run integration test inside docker compose
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker compose -f ./docker-compose-test.yml up --abort-on-container-exit --build

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
