name: unit_tests

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make .env file and run unit-tests inside docker
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker build -f Dockerfile_unittests . -t auth_unittests
          docker run --env-file .env auth_unittests
